### ISSUE TITLE
subdomain c9ui.domain.com

### ISSUE THREAD

**Issue by StijnBousard** [orditeck/c9ui#12]
Hi,

following your suggestion in issue #10, I'm trying to use subdomain c9ui.domain.com.

So I reinstalled c9ui in $HOME/public_html/c9ui (instead of $HOME/c9ui) and created a subdomain (in DirectAdmin) c9ui.<domain>.be.

However, if I go to c9ui.<domain>.be/public, I get the following error:
NotFoundHttpException in Application.php line 1264:

That's the following file:
/domains/<domain>.be/public_html/c9ui/vendor/laravel/lumen-framework/src/Application.php
And the line states:
                throw new NotFoundHttpException;

However, c9ui can be used if I issue  php artisan serve --host=<domain>.be.
Then I can access c9ui by navigating to http://<domain>.be:8000.

What do I do wrong to get it working on c9ui.<domain>.be?

Kind regards

Stijn

**Comment by orditeck** [comment]
Hi,

The `public` folder is the Document Root that should be served by your HTTP Server.

So `c9ui.domain.be` should point to `/domains/.be/public_html/c9ui/public`, **not** `/domains/.be/public_html/c9ui`.

You should then use `c9ui.domain.be`, **not** `c9ui.domain.be/public`. 

Note:
You could however use it as you are right now. You'd just have to set `RewriteBase` to `/public` in your `public/.htaccess` but that would be really bad because the whole Lumen app would be publicly accessible and you don't want that. Sure you could restrict access to those files but it's way way simpler/better to just point your Document Root to `/public`. I don't know if you understood what I just said here but I felt like I needed to add this note to make sure you understand all your possibilities. Just don't use that one lol. 

The reason behind your issue is that Lumen's routing starts at `/`. When requesting `/public`, Lumen actually think that you're requesting the following route: `/public`! But it doesn't exist. As simple as that.

**Comment by StijnBousard** [comment]
Marvellous!

I'm not a hero in Apache, but your explanation was crystal clear and the following site helped me to create the right .htaccess file to change my document root for c9ui.domain.be so that it points to the public subdir:
https://www.siteground.com/kb/how_to_change_my_document_root_folder_using_an_htaccess_file/

Now I'm able to launch my c9 dev envs without the need of launching an ssh command in a separate window.

Thanks a lot!

Stijn
