### ISSUE TITLE
How to run c9ui on different machine(vps)

### ISSUE THREAD

**Issue by rinodung** [orditeck/c9ui#2]
I have a linux vps which is running C9, and another vps run c9ui web, It's possible to control my C9 service by connect to a specific IP(xxx.xxx.xxx.xxx) from my C9UI website?

**Comment by orditeck** [comment]
c9ui has been made to manage c9 on the same machine that c9ui is running on.

What you're asking can be done, but you'll need to write up some code, and maybe change the logic of the app. Right now it allows one running instance of c9, my guess is that you'll want to remove that to run multiple running instances of c9 on different VPS. You could use [`ssh2_exec`](http://php.net/manual/en/function.ssh2-exec.php) instead of `shell_exec`. 

As you can see in WorkflowController.php [on line 94](https://github.com/orditeck/c9ui/blob/master/app/Http/Controllers/WorkflowController.php#L94) and [on line 118](https://github.com/orditeck/c9ui/blob/master/app/Http/Controllers/WorkflowController.php#L114), commands are directly executed on the same server that c9ui runs on.
